name: Release repo
on:
  push:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'release-repo: v')"

    steps:
      - uses: actions/checkout@v2

      - name: release
        run: |
          sh ./scripts/release-repo.sh ${{ secrets.GITHUB_TOKEN }} "${{ github.event.head_commit.message }}"
